image: python:2.7

variables: 
  DEFAULT_PLATFORMIO_PROJECT_CONF_FILE: platformio.ini

cache:
  paths:
    - "~/.platformio"
    - "$CI_PROJECT_DIR/pip-cache"

stages:
 - build

build:init:
  stage: build
  script: 
    - "platformio ci --project-conf=$DEFAULT_PLATFORMIO_PROJECT_CONF_FILE"
  variables: {PLATFORMIO_CI_SRC: "Turpial/Turpial.ino"}
  only:
    - /^sprint.*$/
    - devel
  when: always

.prepare_env: &prepare_env |
  function install_platformio {
    pip install -U platformio
    platformio update
  }

before_script:
#  - *prepare_env
  - pip install -U platformio

