image: python:2.7

variables: 
  DEFAULT_PLATAFORMIO_PROJECT_CONF_FILE: plataformio.ini

cache:
  paths:
    - "~/.platformio"

stages:
 - build

before_script:
  - "pip install -U platformio"

build:init:
  stage: build
  script: 
    - "plataformio ci --project-conf=$DEFAULT_PLATAFORMIO_PROJECT_CONF_FILE"
  only:
    - /^sprint.*$/
  when: always

.prepare_env: &prepare_env |
  function install_plataformio {
    pip install -U plataformio
    #platformio update
  }

before_script:
  - pip install -U plataformio
#  - *prepare_env

