image: python:2.7

stages:
 - test

before_script:
  - "pip install -U platformio"

job:
  stage: test
  script: "platformio ci -C Turpail/plataformio.ini"
  variables: {PLATFORMIO_CI_SRC: "Turpial/src/Turpial.ino"}