image: python:2.7

variables: 
#  GIT_SUBMODULE_STRATEGY: recursive
  DEFAULT_PLATFORMIO_PROJECT_CONF_FILE: platformio.ini

cache:
  paths:
    - "~/.platformio"
    - "$CI_PROJECT_DIR/pip-cache"

stages:
 - build

build:init:
  stage: build
  script: 
    - "platformio ci --project-conf=$DEFAULT_PLATFORMIO_PROJECT_CONF_FILE"
  variables: 
    PLATFORMIO_CI_SRC: "Turpial/Turpial.ino"
    PLATFORMIO_LIB_EXTRA_DIRS: "Turpial/lib"
  only:
    - /^sprint.*$/
    - devel
  when: always

.prepare_env: &prepare_env |
  function install_platformio {
    pip install -U platformio
    platformio update
  }
  function tune_image_on_the_fly {
    apt install ssh -y
    git submodule sync --recursive
    git submodule update --init --recursive
  }

before_script:
  - *prepare_env
  - pip install -U platformio

